# Generated by Django 6.0.1 on 2026-02-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='material_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity_wasted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('salary', 'Salary'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('maintenance', 'Maintenance'), ('office', 'Office Supplies'), ('marketing', 'Marketing'), ('wastage', 'Wastage Material'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
