# Generated by Django 6.0.1 on 2026-02-23 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(choices=[('printer', 'Printer'), ('helper', 'Helper'), ('designer', 'Designer'), ('driver', 'Driver'), ('binder', 'Binder'), ('operator', 'Machine Operator'), ('manager', 'Manager'), ('other', 'Other')], default='helper', max_length=50)),
                ('salary_type', models.CharField(choices=[('daily', 'Daily Wage'), ('monthly', 'Monthly Salary')], default='daily', max_length=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_working_days', models.IntegerField(default=0)),
                ('days_present', models.IntegerField(default=0)),
                ('half_days', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('leaves', models.IntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Pay Slip',
                'verbose_name_plural': 'Pay Slips',
                'db_table': 'staff_payslips',
                'ordering': ['-year', '-month', 'staff__name'],
                'unique_together': {('staff', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'Leave')], default='present', max_length=10)),
                ('overtime_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'staff_attendance',
                'ordering': ['-date', 'staff__name'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
