# Generated by Django 6.0.1 on 2026-02-23 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0007_joborder_payment_terms'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(blank=True, max_length=300)),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='joborders.joborder')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Worker Assignment',
                'verbose_name_plural': 'Worker Assignments',
                'db_table': 'worker_assignments',
                'ordering': ['assigned_at'],
                'unique_together': {('job_order', 'staff')},
            },
        ),
    ]
