# Generated by Django 6.0.1 on 2026-02-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_workerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='holidays_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='sundays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('helper', 'Helper'), ('designer', 'Designer'), ('driver', 'Driver'), ('operator', 'Machine Operator'), ('manager', 'Manager'), ('other', 'Other')], default='helper', max_length=50),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('government', 'Government Holiday'), ('festival', 'Festival Holiday'), ('company', 'Company Holiday')], default='government', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'staff_holidays',
                'ordering': ['date'],
                'unique_together': {('name', 'date')},
            },
        ),
    ]
