# Generated by Django 6.0.1 on 2026-01-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('pan', models.CharField(blank=True, max_length=10, verbose_name='PAN')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='company/signatures/')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=50)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('invoice_start_number', models.IntegerField(default=1)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
            },
        ),
    ]
