# Generated by Django 6.0.1 on 2026-02-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
