# Generated by Django 6.0.1 on 2026-01-31 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material Type',
                'verbose_name_plural': 'Material Types',
                'db_table': 'material_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Printing Type',
                'verbose_name_plural': 'Printing Types',
                'db_table': 'printing_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('design', 'Design Work'), ('printing', 'Printing'), ('finishing', 'Finishing'), ('other', 'Other')], default='other', max_length=20)),
                ('rate_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('per_meter', 'Per Meter'), ('per_piece', 'Per Piece'), ('per_color', 'Per Color'), ('per_sqm', 'Per Square Meter')], default='fixed', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Rate',
                'verbose_name_plural': 'Service Rates',
                'db_table': 'service_rates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('job_date', models.DateField(auto_now_add=True)),
                ('material_description', models.CharField(blank=True, max_length=200)),
                ('material_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_unit', models.CharField(choices=[('MTR', 'Meters'), ('PCS', 'Pieces'), ('ROLL', 'Rolls'), ('KG', 'Kilograms'), ('SQM', 'Square Meters')], default='MTR', max_length=10)),
                ('design_name', models.CharField(max_length=200)),
                ('design_file', models.FileField(blank=True, null=True, upload_to='job_designs/')),
                ('design_notes', models.TextField(blank=True)),
                ('design_provided_by_customer', models.BooleanField(default=False)),
                ('num_colors', models.IntegerField(default=1)),
                ('color_details', models.TextField(blank=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('designing', 'Designing'), ('color_separation', 'Color Separation'), ('printing', 'Printing'), ('drying', 'Drying'), ('finishing', 'Finishing'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('express', 'Express')], default='normal', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('internal_notes', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_orders', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='invoices.invoice')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='joborders.materialtype')),
                ('printing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='joborders.printingtype')),
            ],
            options={
                'verbose_name': 'Job Order',
                'verbose_name_plural': 'Job Orders',
                'db_table': 'job_orders',
                'ordering': ['-job_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='joborders.joborder')),
            ],
            options={
                'verbose_name': 'Job Status History',
                'verbose_name_plural': 'Job Status History',
                'db_table': 'job_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='unit', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='joborders.joborder')),
                ('service_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joborders.servicerate')),
            ],
            options={
                'verbose_name': 'Job Order Service',
                'verbose_name_plural': 'Job Order Services',
                'db_table': 'job_order_services',
            },
        ),
    ]
