# Generated by Django 6.0.1 on 2026-01-31 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('joborders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_orders', to='customers.customer'),
        ),
    ]
