# Generated by Django 6.0.1 on 2026-01-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0002_joborder_customer_name_alter_joborder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='material_type_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
