# Generated by Django 6.0.1 on 2026-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0003_joborder_material_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='printing_type_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
