# Generated by Django 6.0.1 on 2026-02-01 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0004_joborder_printing_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='assigned_workers',
            field=models.ManyToManyField(blank=True, help_text='Staff members assigned to this job', limit_choices_to={'role': 'staff'}, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joborder',
            name='num_screens',
            field=models.IntegerField(default=0, help_text='Number of screens/stencils created'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='screen_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One-time screen setup cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='joborder',
            name='screen_details',
            field=models.TextField(blank=True, help_text='Screen specifications or notes'),
        ),
    ]
