# Generated by Django 6.0.1 on 2026-02-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0005_add_screen_and_worker_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='design_image',
            field=models.ImageField(blank=True, help_text="Customer's digital design file (logo, artwork, pattern)", null=True, upload_to='job_designs/%Y/%m/'),
        ),
    ]
