# Generated by Django 6.0.1 on 2026-02-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0006_add_design_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='payment_terms',
            field=models.IntegerField(choices=[(0, 'Due on Receipt'), (7, 'Net 7 Days'), (15, 'Net 15 Days'), (30, 'Net 30 Days'), (45, 'Net 45 Days'), (60, 'Net 60 Days')], default=15, help_text='Number of days until payment is due'),
        ),
    ]
