# Generated by Django 6.0.1 on 2026-02-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0008_simplify_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Estimated hours to complete this job', max_digits=6),
        ),
        migrations.AddField(
            model_name='joborder',
            name='work_started_at',
            field=models.DateTimeField(blank=True, help_text='Auto-set when status changes to finishing', null=True),
        ),
    ]
