# Generated by Django 6.0.1 on 2026-01-30 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU/Code')),
                ('hsn_code', models.CharField(blank=True, max_length=20, verbose_name='HSN/SAC Code')),
                ('description', models.TextField(blank=True)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='MRP')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='GST Rate %')),
                ('is_inclusive', models.BooleanField(default=False, verbose_name='Price Inclusive of Tax')),
                ('quantity', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=10, verbose_name='Minimum Stock Level')),
                ('max_stock', models.IntegerField(default=1000, verbose_name='Maximum Stock Level')),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('NOS', 'Numbers'), ('KG', 'Kilograms'), ('GM', 'Grams'), ('MTR', 'Meters'), ('CM', 'Centimeters'), ('LTR', 'Liters'), ('ML', 'Milliliters'), ('BOX', 'Box'), ('PAC', 'Pack'), ('SET', 'Set'), ('SQM', 'Square Meters'), ('SQFT', 'Square Feet')], default='PCS', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_service', models.BooleanField(default=False, verbose_name='Is this a service?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ', 'Adjustment'), ('RET', 'Return')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
