# Generated by Django 6.0.1 on 2026-02-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='job_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment', 'Payment Received'), ('order', 'New Order'), ('invoice', 'Invoice Created'), ('job_order', 'Job Order Update'), ('alert', 'Alert'), ('warning', 'Warning'), ('success', 'Success'), ('info', 'Information')], default='info', max_length=20),
        ),
    ]
